concrete ScanNoOpposite80MoreOutput of ScanNoOpposite80More = ScanOutput ** 
{
	lincat VPopp = {s : Str};
	lin
		UseVPopp vpopp = vpopp ;
		AdvVerbVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbVerbAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvAdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
}
