concrete ScanNoOpposite300MoreOutput of ScanNoOpposite300More = ScanOutput ** 
{
	lincat VPopp = {s : Str};
	lin
		UseVPopp vpopp = vpopp ;
		AdvAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdvVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbVerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerbVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvAdvVerbVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdvAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbVerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvAdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbVerbVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbVerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvVerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbVerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdvAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbVerbVerbVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdvAdvVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbVerbAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvAdvAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbVerbVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdvVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerbAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbAdvVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerbAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvVerbAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbVerbAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerbAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvAdvAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbVerbVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbVerbVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbAdvVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
}
