concrete ScanNoOpposite60MoreInput of ScanNoOpposite60More = ScanInput ** 
{
	lincat VPopp = {s : Str};
	lin
		UseVPopp vpopp = vpopp ;
		AdvVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ "avaaav" ++ adv.s} ;
		VerbAdvAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ "vaavaaa" ++ adv.s} ;
		AdvAdvAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ "aaaavvv" ++ adv.s} ;
		AdvVerbAdv verb adv = {s = verb.s ++ "ava" ++ adv.s} ;
		AdvAdvVerbAdvVerbAdv verb adv = {s = verb.s ++ "aavava" ++ adv.s} ;
		VerbVerbVerbVerbAdv verb adv = {s = verb.s ++ "vvvva" ++ adv.s} ;
		VerbVerbVerbVerbAdvAdvVerb verb adv = {s = verb.s ++ "vvvvaav" ++ adv.s} ;
		VerbVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ "vvaaav" ++ adv.s} ;
		VerbAdvAdvAdvVerbAdvVerbAdv verb adv = {s = verb.s ++ "vaaavava" ++ adv.s} ;
		VerbVerbAdv verb adv = {s = verb.s ++ "vva" ++ adv.s} ;
		AdvVerbVerbVerbAdv verb adv = {s = verb.s ++ "avvva" ++ adv.s} ;
		VerbAdvAdvAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ "vaaaaaaa" ++ adv.s} ;
		AdvVerbAdvVerbAdvAdvVerbAdv verb adv = {s = verb.s ++ "avavaava" ++ adv.s} ;
		VerbVerbVerbVerbVerbVerbVerbAdv verb adv = {s = verb.s ++ "vvvvvvva" ++ adv.s} ;
		VerbVerbVerbVerbAdvVerb verb adv = {s = verb.s ++ "vvvvav" ++ adv.s} ;
		VerbAdvVerbAdv verb adv = {s = verb.s ++ "vava" ++ adv.s} ;
		VerbAdvAdvVerbVerbVerbVerbVerb verb adv = {s = verb.s ++ "vaavvvvv" ++ adv.s} ;
		VerbAdvAdv verb adv = {s = verb.s ++ "vaa" ++ adv.s} ;
		AdvAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ "aavvvv" ++ adv.s} ;
		AdvAdvVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ "aavvaaa" ++ adv.s} ;
		VerbVerbVerbAdv verb adv = {s = verb.s ++ "vvva" ++ adv.s} ;
		AdvVerbVerbAdv verb adv = {s = verb.s ++ "avva" ++ adv.s} ;
		VerbAdvAdvAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ "vaaaavaa" ++ adv.s} ;
		AdvVerbAdvVerb verb adv = {s = verb.s ++ "avav" ++ adv.s} ;
		VerbVerbVerbAdvAdvVerbAdv verb adv = {s = verb.s ++ "vvvaava" ++ adv.s} ;
		AdvVerbAdvAdvVerbVerbAdv verb adv = {s = verb.s ++ "avaavva" ++ adv.s} ;
		AdvVerbAdvAdv verb adv = {s = verb.s ++ "avaa" ++ adv.s} ;
		AdvAdvAdvVerbVerb verb adv = {s = verb.s ++ "aaavv" ++ adv.s} ;
		AdvVerbVerbAdvVerb verb adv = {s = verb.s ++ "avvav" ++ adv.s} ;
		AdvAdvVerbVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ "aavvvaaa" ++ adv.s} ;
		AdvAdvAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ "aaavvaa" ++ adv.s} ;
		VerbVerbAdvAdvVerb verb adv = {s = verb.s ++ "vvaav" ++ adv.s} ;
		AdvAdvVerbVerb verb adv = {s = verb.s ++ "aavv" ++ adv.s} ;
		AdvAdvAdvVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ "aaavaaav" ++ adv.s} ;
		AdvAdvAdvVerb verb adv = {s = verb.s ++ "aaav" ++ adv.s} ;
		VerbAdvVerbVerbAdv verb adv = {s = verb.s ++ "vavva" ++ adv.s} ;
		VerbAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ "vavavv" ++ adv.s} ;
		AdvVerbAdvAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ "avaavvvv" ++ adv.s} ;
		VerbAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ "vavvva" ++ adv.s} ;
		VerbVerbVerbAdvVerb verb adv = {s = verb.s ++ "vvvav" ++ adv.s} ;
		VerbAdvAdvVerbAdv verb adv = {s = verb.s ++ "vaava" ++ adv.s} ;
		AdvAdvVerbVerbVerbVerbVerb verb adv = {s = verb.s ++ "aavvvvv" ++ adv.s} ;
		VerbVerbAdvAdv verb adv = {s = verb.s ++ "vvaa" ++ adv.s} ;
		VerbAdvVerbAdvAdv verb adv = {s = verb.s ++ "vavaa" ++ adv.s} ;
		VerbAdvVerb verb adv = {s = verb.s ++ "vav" ++ adv.s} ;
		AdvAdvVerbAdv verb adv = {s = verb.s ++ "aava" ++ adv.s} ;
		AdvVerbAdvVerbVerbVerb verb adv = {s = verb.s ++ "avavvv" ++ adv.s} ;
		AdvVerbAdvAdvAdv verb adv = {s = verb.s ++ "avaaa" ++ adv.s} ;
		VerbAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ "vavaaa" ++ adv.s} ;
		AdvAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ "aavaav" ++ adv.s} ;
		AdvAdvVerbAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ "aavavvaa" ++ adv.s} ;
		VerbAdvVerbVerbAdvVerb verb adv = {s = verb.s ++ "vavvav" ++ adv.s} ;
		AdvAdvAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ "aaavavv" ++ adv.s} ;
		AdvAdvVerbAdvVerb verb adv = {s = verb.s ++ "aavav" ++ adv.s} ;
		AdvVerbVerbVerb verb adv = {s = verb.s ++ "avvv" ++ adv.s} ;
		VerbVerbVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ "vvvaavv" ++ adv.s} ;
		AdvAdvAdvVerbVerbVerbVerbVerb verb adv = {s = verb.s ++ "aaavvvvv" ++ adv.s} ;
		AdvAdvVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ "aavvvaa" ++ adv.s} ;
		AdvVerbVerb verb adv = {s = verb.s ++ "avv" ++ adv.s} ;
		VerbVerbAdvVerb verb adv = {s = verb.s ++ "vvav" ++ adv.s} ;
}
