concrete ScanNoOpposite150MoreOutput of ScanNoOpposite150More = ScanOutput ** 
{
	lincat VPopp = {s : Str};
	lin
		UseVPopp vpopp = vpopp ;
		VerbAdvAdvVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvVerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvVerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbVerbAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbAdvAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerbAdvAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerbAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbAdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbVerbAdvVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvAdvAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
}
