concrete ScanNoOpposite240MoreOutput of ScanNoOpposite240More = ScanOutput ** 
{
	lincat VPopp = {s : Str};
	lin
		UseVPopp vpopp = vpopp ;
		AdvAdvAdvVerbVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvAdvVerbAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbVerbAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdvAdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbVerbVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerbVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvVerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbVerbVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbAdvAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbVerbAdvAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbVerbVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbVerbAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvAdvAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbAdvVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvVerbVerbVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbVerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvAdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbVerbAdvVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdvAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvAdvAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
}
