concrete ScanNoOpposite200MoreOutput of ScanNoOpposite200More = ScanOutput ** 
{
	lincat VPopp = {s : Str};
	lin
		UseVPopp vpopp = vpopp ;
		VerbVerbAdvAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbVerbAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbVerbVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerbVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdvAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbVerbVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbAdvVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdvAdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerbAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdvAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
}
