concrete ScanNoOpposite120MoreOutput of ScanNoOpposite120More = ScanOutput ** 
{
	lincat VPopp = {s : Str};
	lin
		UseVPopp vpopp = vpopp ;
		AdvAdvVerbAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvVerbAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvVerbAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvVerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbVerbAdvVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvAdvAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbVerbVerbVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbVerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdvAdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbVerbAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbAdvAdvAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbAdvAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdvVerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		AdvAdvAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbAdvAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbAdvVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		AdvAdvAdvVerbAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvAdvVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdvAdvVerbVerb verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbVerb verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		AdvVerbVerbAdvAdvAdvAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbAdvAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvAdvVerbVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbVerbVerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvVerbAdvAdvAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvAdvVerbVerbVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbVerbVerbVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		VerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ adv.s} ;
		AdvVerbAdvVerbVerbVerbAdvAdv verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbVerbAdvAdv verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s} ;
		AdvAdvVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		VerbAdvAdvAdvVerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		VerbAdvAdvAdvVerbAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbAdvVerbAdv verb adv = {s = verb.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbAdvVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s} ;
		VerbVerbAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvAdvAdvVerbAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s} ;
		VerbAdvAdvVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvAdvAdvVerbAdvAdv verb adv = {s = adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s ++ adv.s ++ adv.s} ;
		VerbVerbAdvAdvAdvAdvAdvVerb verb adv = {s = verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ adv.s ++ verb.s} ;
		VerbVerbVerbVerbVerbVerbAdv verb adv = {s = verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbAdvAdvVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ verb.s} ;
		AdvVerbAdvVerbAdvVerb verb adv = {s = adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvAdvVerbVerbAdvAdvAdv verb adv = {s = verb.s ++ adv.s ++ adv.s ++ verb.s ++ verb.s ++ adv.s ++ adv.s ++ adv.s} ;
		AdvVerbVerbAdv verb adv = {s = adv.s ++ verb.s ++ verb.s ++ adv.s} ;
		AdvVerbVerbVerb verb adv = {s = adv.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbVerbVerbVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
		AdvAdvVerbAdvVerbAdvVerb verb adv = {s = adv.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s ++ adv.s ++ verb.s} ;
		VerbAdvVerbVerbVerbVerb verb adv = {s = verb.s ++ adv.s ++ verb.s ++ verb.s ++ verb.s ++ verb.s} ;
}
