concrete CogsLexiconFin of CogsLexicon = CogsFin ** open MorphoFin, StemFin, ParadigmsFin, Kotus in {
lin
--     tv_N 		= mkN "TV" ;
    baby_N 		    = mkN {s = d09 "vauva"} ;
    backpack_N 		= mkN {s = d01A "reppu"} ;
    backyard_N 		= mkN {s = d09 "piha"} ;
    bag_N 		    = mkN {s = d05 "kassi"} ;
    bakery_N 		= mkN {s = d02 "leipomo"} ;
    ball_N 		    = mkN {s = d01 "pallo"} ;
    balloon_N 		= mkN {s = d01 "ilmapallo"} ;
    banana_N 		= mkN {s = d06 "banaani"} ;
    baron_N 		= mkN {s = d06 "baroni"} ;
    barrel_N 		= mkN {s = d01A "piippu"} ;
    basin_N 		= mkN {s = d05 "lavuaari"} ;
    basket_N 		= mkN {s = d05 "kori"} ;
    bat_N 		    = mkN {s = d04A "lepakko"} ;
    bathtub_N       = mkN {s = dxx "amme"} ;
    beach_N         = mkN {s = dxx "ranta"} ;
    bean_N          = mkN {s = dxx "papu"} ;
    bear_N          = mkN {s = dxx "karhu"} ;
    beast_N         = mkN {s = dxx "peto"} ;
    bed_N           = mkN {s = dxx "sänky"} ;
    bee_N           = mkN {s = dxx "mehiläinen"} ;
    beer_N          = mkN {s = dxx "olut"} ;
    bell_N          = mkN {s = dxx "kello"} ;
    bench_N         = mkN {s = dxx "penkki"} ;
    bible_N         = mkN {s = dxx "raamattu"} ;
    bicycle_N       = mkN {s = dxx "polkupyörä"} ;
    bike_N          = mkN {s = dxx "pyörä"} ;
    bin_N           = mkN {s = dxx "roska-astia"} ;
    bird_N = mkN {s = dxx "lintu"} ;
    biscuit_N = mkN {s = dxx "keksi"} ;
    blanket_N = mkN {s = dxx "peitto"} ;
    blender_N = mkN {s = dxx "tehosekoitin"} ;
    block_N = mkN {s = dxx "lohko"} ;
    board_N = mkN {s = dxx "lauta"} ;
    boat_N = mkN {s = dxx "vene"} ;
    book_N = mkN {s = dxx "kirja"} ;
    booklet_N = mkN {s = dxx "vihko"} ;
    bookstore_N = mkN {s = dxx "kirjakauppa"} ;
    bottle_N = mkN {s = dxx "pullo"} ;
    boulder_N = mkN {s = dxx "kivenjärkäle"} ;
    bowl_N = mkN {s = dxx "kulho"} ;
    box_N = mkN {s = dxx "laatikko"} ;
    boy_N = mkN {s = dxx "poika"} ;
    brain_N = mkN {s = dxx "aivot"} ;
    branch_N = mkN {s = dxx "oksa"} ;
    brick_N = mkN {s = dxx "tiili"} ;
    broker_N = mkN {s = dxx "välittäjä"} ;
    brush_N = mkN {s = dxx "harja"} ;
    bucket_N = mkN {s = dxx "ämpäri"} ;
    bun_N = mkN {s = dxx "sämpylä"} ;
    bunker_N = mkN {s = dxx "bunkkeri"} ;
    bunny_N = mkN {s = dxx "pupu"} ;
    bush_N = mkN {s = dxx "pensas"} ;
    butterfly_N = mkN {s = dxx "perhonen"} ;
    button_N = mkN {s = dxx "nappi"} ;
    buyer_N = mkN {s = dxx "ostaja"} ;
    cabinet_N = mkN {s = dxx "kaappi"} ;
    cafe_N = mkN {s = dxx "kahvila"} ;
    cage_N = mkN {s = dxx "häkki"} ;
    cake_N = mkN {s = dxx "kakku"} ;
    can_N = mkN {s = dxx "tölkki"} ;
    canvas_N = mkN {s = dxx "kangas"} ;
    captain_N = mkN {s = dxx "kapteeni"} ;
    car_N = mkN {s = dxx "auto"} ;
    carpet_N = mkN {s = dxx "matto"} ;
    cart_N = mkN {s = dxx "kärry"} ;
    casket_N = mkN {s = dxx "arkku"} ;
    cassette_N = mkN {s = dxx "kasetti"} ;
    castle_N = mkN {s = dxx "linna"} ;
    cat_N = mkN {s = dxx "kissa"} ;
    chair_N = mkN {s = dxx "tuoli"} ;
    chalk_N = mkN {s = dxx "liitu"} ;
    champion_N = mkN {s = dxx "mestari"} ;
    chemical_N = mkN {s = dxx "kemikaali"} ;
    chemist_N = mkN {s = dxx "kemisti"} ;
    chessboard_N = mkN {s = dxx "shakkilauta"} ;
    chicken_N = mkN {s = dxx "kana"} ;
    chief_N = mkN {s = dxx "päällikkö"} ;
    child_N = mkN {s = dxx "lapsi"} ;
    china_N = mkN {s = dxx "posliini"} ;
    citizen_N = mkN {s = dxx "kansalainen"} ;
    clock_N = mkN {s = dxx "kello"} ;
    closet_N = mkN {s = dxx "vaatekaappi"} ;
    cloth_N = mkN {s = dxx "kangas"} ;
    cloud_N = mkN {s = dxx "pilvi"} ;
    coach_N = mkN {s = dxx "valmentaja"} ;
    cobra_N = mkN {s = dxx "kobra"} ;
    cockroach_N = mkN {s = dxx "torakka"} ;
    coffin_N = mkN {s = dxx "arkku"} ;
    coin_N = mkN {s = dxx "kolikko"} ;
    computer_N = mkN {s = dxx "tietokone"} ;
    condo_N = mkN {s = dxx "asunto-osake"} ;
    consumer_N = mkN {s = dxx "kuluttaja"} ;
    container_N = mkN {s = dxx "kontti"} ;
    cookie_N = mkN {s = dxx "keksi"} ;
    corner_N = mkN {s = dxx "kulma"} ;
    corpse_N = mkN {s = dxx "ruumis"} ;
    cot_N = mkN {s = dxx "pinnasänky"} ;
    couch_N = mkN {s = dxx "sohva"} ;
    counter_N = mkN {s = dxx "tiski"} ;
    cow_N = mkN {s = dxx "lehmä"} ;
    crack_N = mkN {s = dxx "halkeama"} ;
    cracker_N = mkN {s = dxx "keksi"} ;
    crate_N = mkN {s = dxx "laatikko"} ;
    crayon_N = mkN {s = dxx "värikynä"} ;
    creature_N = mkN {s = dxx "olento"} ;
    crib_N = mkN {s = dxx "kehto"} ;
    crocodile_N = mkN {s = dxx "krokotiili"} ;
    crown_N = mkN {s = dxx "kruunu"} ;
    crystal_N = mkN {s = dxx "kristalli"} ;
    cubicle_N = mkN {s = dxx "koppi"} ;
    cup_N = mkN {s = dxx "kuppi"} ;
    cupboard_N = mkN {s = dxx "kaappi"} ;
    cushion_N = mkN {s = dxx "tyyny"} ;
    customer_N = mkN {s = dxx "asiakas"} ;
    cylinder_N = mkN {s = dxx "sylinteri"} ;
    dealer_N = mkN {s = dxx "kauppias"} ;
    deck_N = mkN {s = dxx "kansi"} ;
    deer_N = mkN {s = dxx "peura"} ;
    desk_N = mkN {s = dxx "kirjoituspöytä"} ;
    device_N = mkN {s = dxx "laite"} ;
    director_N = mkN {s = dxx "johtaja"} ;
    dish_N      = mkN {s = dxx "astia"} ;
    doctor_N        = mkN {s = dxx "lääkäri"} ;
    dog_N       = mkN {s = dxx "koira"} ;
    doll_N      = mkN {s = dxx "nukke"} ;
--     donkey_N 		= mkN "donkey" ;
--     donut_N 		= mkN "donut" ;
--     dragon_N 		= mkN "dragon" ;
--     drawer_N 		= mkN "drawer" ;
--     drink_N 		= mkN "drink" ;
--     driver_N 		= mkN "driver" ;
--     duck_N 		= mkN "duck" ;
--     duke_N 		= mkN "duke" ;
--     dumpster_N 		= mkN "dumpster" ;
--     dungeon_N 		= mkN "dungeon" ;
--     envelope_N 		= mkN "envelope" ;
--     farmer_N 		= mkN "farmer" ;
--     father_N 		= mkN "father" ;
--     fig_N 		= mkN "fig" ;
--     fish_N 		= mkN "fish" ;
--     fishbowl_N 		= mkN "fishbowl" ;
--     flag_N 		= mkN "flag" ;
--     floor_N 		= mkN "floor" ;
--     flower_N 		= mkN "flower" ;
--     fly_N 		= mkN "fly" ;
--     foreigner_N 		= mkN "foreigner" ;
--     fox_N 		= mkN "fox" ;
--     fridge_N 		= mkN "fridge" ;
--     friend_N 		= mkN "friend" ;
--     frog_N 		= mkN "frog" ;
--     fruit_N 		= mkN "fruit" ;
--     futon_N 		= mkN "futon" ;
--     game_N 		= mkN "game" ;
--     garden_N 		= mkN "garden" ;
--     gardner_N 		= mkN "gardner" ;
--     genius_N 		= mkN "genius" ;
--     giant_N 		= mkN "giant" ;
--     giraffe_N 		= mkN "giraffe" ;
--     girl_N 		= mkN "girl" ;
--     glacier_N 		= mkN "glacier" ;
--     glass_N 		= mkN "glass" ;
--     glue_N 		= mkN "glue" ;
--     goose_N 		= mkN "goose" ;
--     governor_N 		= mkN "governor" ;
--     gravel_N 		= mkN "gravel" ;
--     guard_N 		= mkN "guard" ;
--     guest_N 		= mkN "guest" ;
--     guitar_N 		= mkN "guitar" ;
--     gumball_N 		= mkN "gumball" ;
--     guy_N 		= mkN "guy" ;
--     hamburger_N 		= mkN "hamburger" ;
--     hammer_N 		= mkN "hammer" ;
--     hammock_N 		= mkN "hammock" ;
--     hanger_N 		= mkN "hanger" ;
--     hat_N 		= mkN "hat" ;
--     haystack_N 		= mkN "haystack" ;
--     headmaster_N 		= mkN "headmaster" ;
--     hedge_N 		= mkN "hedge" ;
--     helicopter_N 		= mkN "helicopter" ;
--     hen_N 		= mkN "hen" ;
--     hero_N 		= mkN "hero" ;
--     hole_N 		= mkN "hole" ;
--     horse_N 		= mkN "horse" ;
--     host_N 		= mkN "host" ;
--     house_N 		= mkN "house" ;
--     human_N 		= mkN "human" ;
--     jacket_N 		= mkN "jacket" ;
--     jar_N 		= mkN "jar" ;
--     jeep_N 		= mkN "jeep" ;
--     jigsaw_N 		= mkN "jigsaw" ;
--     journalist_N 		= mkN "journalist" ;
--     judge_N 		= mkN "judge" ;
--     kennel_N 		= mkN "kennel" ;
--     key_N 		= mkN "key" ;
--     keyboard_N 		= mkN "keyboard" ;
--     kid_N 		= mkN "kid" ;
--     king_N 		= mkN "king" ;
--     kitty_N 		= mkN "kitty" ;
--     knife_N 		= mkN "knife" ;
--     ladder_N 		= mkN "ladder" ;
--     lamb_N 		= mkN "lamb" ;
--     lamp_N 		= mkN "lamp" ;
--     landlord_N 		= mkN "landlord" ;
--     lawyer_N 		= mkN "lawyer" ;
--     leaf_N 		= mkN "leaf" ;
--     leaflet_N 		= mkN "leaflet" ;
--     lemon_N 		= mkN "lemon" ;
--     lion_N 		= mkN "lion" ;
--     liver_N 		= mkN "liver" ;
--     log_N 		= mkN "log" ;
--     lollipop_N 		= mkN "lollipop" ;
--     machine_N 		= mkN "machine" ;
--     manager_N 		= mkN "manager" ;
--     mandarin_N 		= mkN "mandarin" ;
--     mattress_N 		= mkN "mattress" ;
--     melon_N 		= mkN "melon" ;
--     microwave_N 		= mkN "microwave" ;
--     mirror_N 		= mkN "mirror" ;
--     molecule_N 		= mkN "molecule" ;
--     monastery_N 		= mkN "monastery" ;
--     monk_N 		= mkN "monk" ;
--     monkey_N 		= mkN "monkey" ;
--     monster_N 		= mkN "monster" ;
--     moose_N 		= mkN "moose" ;
--     mother_N 		= mkN "mother" ;
--     mound_N 		= mkN "mound" ;
--     mouse_N 		= mkN "mouse" ;
--     muffin_N 		= mkN "muffin" ;
--     mug_N 		= mkN "mug" ;
--     murderer_N 		= mkN "murderer" ;
--     nail_N 		= mkN "nail" ;
--     napkin_N 		= mkN "napkin" ;
--     needle_N 		= mkN "needle" ;
--     nest_N 		= mkN "nest" ;
--     newspaper_N 		= mkN "newspaper" ;
--     notebook_N 		= mkN "notebook" ;
--     package_N 		= mkN "package" ;
--     pad_N 		= mkN "pad" ;
--     painting_N 		= mkN "painting" ;
--     palace_N 		= mkN "palace" ;
--     pancake_N 		= mkN "pancake" ;
--     panel_N 		= mkN "panel" ;
--     paper_N 		= mkN "paper" ;
--     parcel_N 		= mkN "parcel" ;
--     passenger_N 		= mkN "passenger" ;
--     patient_N 		= mkN "patient" ;
--     pedestal_N 		= mkN "pedestal" ;
--     pen_N 		= mkN "pen" ;
--     pencil_N 		= mkN "pencil" ;
--     penguin_N 		= mkN "penguin" ;
--     penny_N 		= mkN "penny" ;
--     penthouse_N 		= mkN "penthouse" ;
--     pepper_N 		= mkN "pepper" ;
--     philosopher_N 		= mkN "philosopher" ;
--     piano_N 		= mkN "piano" ;
--     pickle_N 		= mkN "pickle" ;
--     pig_N 		= mkN "pig" ;
--     pile_N 		= mkN "pile" ;
--     pillar_N 		= mkN "pillar" ;
--     pillow_N 		= mkN "pillow" ;
--     pit_N 		= mkN "pit" ;
--     pizza_N 		= mkN "pizza" ;
--     plant_N 		= mkN "plant" ;
--     plaque_N 		= mkN "plaque" ;
--     plate_N 		= mkN "plate" ;
--     platter_N 		= mkN "platter" ;
--     pod_N 		= mkN "pod" ;
--     podium_N 		= mkN "podium" ;
--     poet_N 		= mkN "poet" ;
--     politician_N 		= mkN "politician" ;
--     pony_N 		= mkN "pony" ;
--     pool_N 		= mkN "pool" ;
--     poster_N 		= mkN "poster" ;
--     pot_N 		= mkN "pot" ;
--     potato_N 		= mkN "potato" ;
--     present_N 		= mkN "present" ;
--     president_N 		= mkN "president" ;
--     pretzel_N 		= mkN "pretzel" ;
--     priest_N 		= mkN "priest" ;
--     prince_N 		= mkN "prince" ;
--     princess_N 		= mkN "princess" ;
--     prisoner_N 		= mkN "prisoner" ;
--     producer_N 		= mkN "producer" ;
--     professor_N 		= mkN "professor" ;
--     puddle_N 		= mkN "puddle" ;
--     pumpkin_N 		= mkN "pumpkin" ;
--     pupil_N 		= mkN "pupil" ;
--     puppy_N 		= mkN "puppy" ;
--     purse_N 		= mkN "purse" ;
--     pyramid_N 		= mkN "pyramid" ;
--     queen_N 		= mkN "queen" ;
--     rack_N 		= mkN "rack" ;
--     radio_N 		= mkN "radio" ;
--     rag_N 		= mkN "rag" ;
--     raisin_N 		= mkN "raisin" ;
--     refrigerator_N 		= mkN "refrigerator" ;
--     researcher_N 		= mkN "researcher" ;
--     resident_N 		= mkN "resident" ;
--     ring_N 		= mkN "ring" ;
--     road_N 		= mkN "road" ;
--     rock_N 		= mkN "rock" ;
--     rod_N 		= mkN "rod" ;
--     room_N 		= mkN "room" ;
--     rose_N 		= mkN "rose" ;
--     rug_N 		= mkN "rug" ;
--     sack_N 		= mkN "sack" ;
--     sailor_N 		= mkN "sailor" ;
--     sandwich_N 		= mkN "sandwich" ;
--     saucepan_N 		= mkN "saucepan" ;
--     scarf_N 		= mkN "scarf" ;
--     scientist_N 		= mkN "scientist" ;
--     sculpture_N 		= mkN "sculpture" ;
--     seat_N 		= mkN "seat" ;
--     seed_N 		= mkN "seed" ;
--     servant_N 		= mkN "servant" ;
--     sheep_N 		= mkN "sheep" ;
--     sheet_N 		= mkN "sheet" ;
--     shelf_N 		= mkN "shelf" ;
--     shell_N 		= mkN "shell" ;
--     shirt_N 		= mkN "shirt" ;
--     shoe_N 		= mkN "shoe" ;
--     shoebox_N 		= mkN "shoebox" ;
--     sink_N 		= mkN "sink" ;
--     skull_N 		= mkN "skull" ;
--     soap_N 		= mkN "soap" ;
--     sock_N 		= mkN "sock" ;
--     sofa_N 		= mkN "sofa" ;
--     soldier_N 		= mkN "soldier" ;
--     soup_N 		= mkN "soup" ;
--     spaceship_N 		= mkN "spaceship" ;
--     speaker_N 		= mkN "speaker" ;
--     sphere_N 		= mkN "sphere" ;
--     spokesman_N 		= mkN "spokesman" ;
--     spoon_N 		= mkN "spoon" ;
--     squirrel_N 		= mkN "squirrel" ;
--     stack_N 		= mkN "stack" ;
--     stadium_N 		= mkN "stadium" ;
--     stage_N 		= mkN "stage" ;
--     stand_N 		= mkN "stand" ;
--     statue_N 		= mkN "statue" ;
--     stool_N 		= mkN "stool" ;
--     storage_N 		= mkN "storage" ;
--     strawberry_N 		= mkN "strawberry" ;
--     student_N 		= mkN "student" ;
--     surface_N 		= mkN "surface" ;
--     surgeon_N 		= mkN "surgeon" ;
--     swamp_N 		= mkN "swamp" ;
--     sweetcorn_N 		= mkN "sweetcorn" ;
--     sword_N 		= mkN "sword" ;
--     table_N 		= mkN "table" ;
--     tabletop_N 		= mkN "tabletop" ;
--     taxi_N 		= mkN "taxi" ;
--     teacher_N 		= mkN "teacher" ;
--     teapot_N 		= mkN "teapot" ;
--     tenant_N 		= mkN "tenant" ;
--     tent_N 		= mkN "tent" ;
--     throne_N 		= mkN "throne" ;
--     tiger_N 		= mkN "tiger" ;
--     tin_N 		= mkN "tin" ;
--     tomb_N 		= mkN "tomb" ;
--     tool_N 		= mkN "tool" ;
--     toothbrush_N 		= mkN "toothbrush" ;
--     torch_N 		= mkN "torch" ;
--     tourist_N 		= mkN "tourist" ;
--     towel_N 		= mkN "towel" ;
--     tower_N 		= mkN "tower" ;
--     toy_N 		= mkN "toy" ;
--     trailer_N 		= mkN "trailer" ;
--     train_N 		= mkN "train" ;
--     trainee_N 		= mkN "trainee" ;
--     trampoline_N 		= mkN "trampoline" ;
--     trap_N 		= mkN "trap" ;
--     tray_N 		= mkN "tray" ;
--     tree_N 		= mkN "tree" ;
--     tripod_N 		= mkN "tripod" ;
--     trophy_N 		= mkN "trophy" ;
--     truck_N 		= mkN "truck" ;
--     trunk_N 		= mkN "trunk" ;
--     tub_N 		= mkN "tub" ;
--     tube_N 		= mkN "tube" ;
--     turkey_N 		= mkN "turkey" ;
--     turntable_N 		= mkN "turntable" ;
--     turtle_N 		= mkN "turtle" ;
--     valve_N 		= mkN "valve" ;
--     van_N 		= mkN "van" ;
--     vase_N 		= mkN "vase" ;
--     vehicle_N 		= mkN "vehicle" ;
--     vessel_N 		= mkN "vessel" ;
--     visitor_N 		= mkN "visitor" ;
--     wagon_N 		= mkN "wagon" ;
--     wardrobe_N 		= mkN "wardrobe" ;
--     warrior_N 		= mkN "warrior" ;
--     watch_N 		= mkN "watch" ;
--     weapon_N 		= mkN "weapon" ;
--     well_N 		= mkN "well" ;
--     whale_N 		= mkN "whale" ;
--     windowsill_N 		= mkN "windowsill" ;
--     wine_N 		= mkN "wine" ;
--     wolf_N 		= mkN "wolf" ;
--     worm_N 		= mkN "worm" ;
--     writer_N 		= mkN "writer" ;
--     yacht_N 		= mkN "yacht" ;
--     yogurt_N 		= mkN "yogurt" ;
--     zebra_N 		= mkN "zebra" ;

    abigail_PN 		= mkPN (mkN "Abigail") ;
--     addison_PN 		= mkPN "Addison" ;
--     aiden_PN 		= mkPN "Aiden" ;
--     alexander_PN 		= mkPN "Alexander" ;
--     amelia_PN 		= mkPN "Amelia" ;
--     andrew_PN 		= mkPN "Andrew" ;
--     anthony_PN 		= mkPN "Anthony" ;
--     aria_PN 		= mkPN "Aria" ;
--     asher_PN 		= mkPN "Asher" ;
--     aubrey_PN 		= mkPN "Aubrey" ;
--     audrey_PN 		= mkPN "Audrey" ;
--     aurora_PN 		= mkPN "Aurora" ;
--     ava_PN 		= mkPN "Ava" ;
--     avery_PN 		= mkPN "Avery" ;
--     bella_PN 		= mkPN "Bella" ;
--     benjamin_PN 		= mkPN "Benjamin" ;
--     brooklyn_PN 		= mkPN "Brooklyn" ;
--     caleb_PN 		= mkPN "Caleb" ;
--     camila_PN 		= mkPN "Camila" ;
--     carter_PN 		= mkPN "Carter" ;
--     charlotte_PN 		= mkPN "Charlotte" ;
--     chloe_PN 		= mkPN "Chloe" ;
--     christopher_PN 		= mkPN "Christopher" ;
--     claire_PN 		= mkPN "Claire" ;
--     daniel_PN 		= mkPN "Daniel" ;
--     david_PN 		= mkPN "David" ;
--     dylan_PN 		= mkPN "Dylan" ;
--     eleanor_PN 		= mkPN "Eleanor" ;
--     elijah_PN 		= mkPN "Elijah" ;
--     elizabeth_PN 		= mkPN "Elizabeth" ;
--     ella_PN 		= mkPN "Ella" ;
--     ellie_PN 		= mkPN "Ellie" ;
--     emily_PN 		= mkPN "Emily" ;
--     emma_PN 		= mkPN "Emma" ;
--     ethan_PN 		= mkPN "Ethan" ;
--     evelyn_PN 		= mkPN "Evelyn" ;
--     gabriel_PN 		= mkPN "Gabriel" ;
--     grace_PN 		= mkPN "Grace" ;
--     grayson_PN 		= mkPN "Grayson" ;
--     hannah_PN 		= mkPN "Hannah" ;
--     harper_PN 		= mkPN "Harper" ;
--     hazel_PN 		= mkPN "Hazel" ;
--     henry_PN 		= mkPN "Henry" ;
--     isaac_PN 		= mkPN "Isaac" ;
--     isabella_PN 		= mkPN "Isabella" ;
--     jack_PN 		= mkPN "Jack" ;
--     jackson_PN 		= mkPN "Jackson" ;
--     jacob_PN 		= mkPN "Jacob" ;
--     james_PN 		= mkPN "James" ;
--     jaxon_PN 		= mkPN "Jaxon" ;
--     jayden_PN 		= mkPN "Jayden" ;
--     john_PN 		= mkPN "John" ;
--     joseph_PN 		= mkPN "Joseph" ;
--     joshua_PN 		= mkPN "Joshua" ;
--     julian_PN 		= mkPN "Julian" ;
--     layla_PN 		= mkPN "Layla" ;
--     leah_PN 		= mkPN "Leah" ;
--     leo_PN 		= mkPN "Leo" ;
--     levi_PN 		= mkPN "Levi" ;
--     liam_PN 		= mkPN "Liam" ;
--     lillian_PN 		= mkPN "Lillian" ;
--     lily_PN 		= mkPN "Lily" ;
--     lincoln_PN 		= mkPN "Lincoln" ;
--     logan_PN 		= mkPN "Logan" ;
--     lucas_PN 		= mkPN "Lucas" ;
--     luke_PN 		= mkPN "Luke" ;
--     luna_PN 		= mkPN "Luna" ;
--     madison_PN 		= mkPN "Madison" ;
--     mason_PN 		= mkPN "Mason" ;
--     mateo_PN 		= mkPN "Mateo" ;
--     matthew_PN 		= mkPN "Matthew" ;
--     mia_PN 		= mkPN "Mia" ;
--     michael_PN 		= mkPN "Michael" ;
--     mila_PN 		= mkPN "Mila" ;
--     natalie_PN 		= mkPN "Natalie" ;
--     nathan_PN 		= mkPN "Nathan" ;
--     noah_PN 		= mkPN "Noah" ;
--     nora_PN 		= mkPN "Nora" ;
--     oliver_PN 		= mkPN "Oliver" ;
--     olivia_PN 		= mkPN "Olivia" ;
--     owen_PN 		= mkPN "Owen" ;
--     penelope_PN 		= mkPN "Penelope" ;
--     riley_PN 		= mkPN "Riley" ;
--     ryan_PN 		= mkPN "Ryan" ;
--     samuel_PN 		= mkPN "Samuel" ;
--     savannah_PN 		= mkPN "Savannah" ;
--     scarlett_PN 		= mkPN "Scarlett" ;
--     sebastian_PN 		= mkPN "Sebastian" ;
--     skylar_PN 		= mkPN "Skylar" ;
--     sofia_PN 		= mkPN "Sofia" ;
--     sophia_PN 		= mkPN "Sophia" ;
--     stella_PN 		= mkPN "Stella" ;
--     theodore_PN 		= mkPN "Theodore" ;
--     thomas_PN 		= mkPN "Thomas" ;
--     victoria_PN 		= mkPN "Victoria" ;
--     violet_PN 		= mkPN "Violet" ;
--     william_PN 		= mkPN "William" ;
--     wyatt_PN 		= mkPN "Wyatt" ;
--     zoe_PN 		= mkPN "Zoe" ;
--     zoey_PN 		= mkPN "Zoey" ;

    break_VUnacc 		= mkV {s = c52A "särkyä"} ;
    burn_VUnacc 		= mkV {s = c56 "palaa"} ;
--     change_VUnacc 		= mkV "muuttua" ;
--     collapse_VUnacc 		= mkV "romahtaa" ;
--     crumple_VUnacc 		= mkV "sortua" ;
--     decompose_VUnacc 		= mkV "hajota" ;
--     disintegrate_VUnacc 		= mkV "levitä" ;
--     double_VUnacc 		= mkV "kaksinkertaistua" ;
--     enlarge_VUnacc 		= mkV "suurentua" ;
--     float_VUnacc 		= mkV "kellua" ;
--     freeze_VUnacc 		= mkV "jäätyä" ;
--     grow_VUnacc 		= mkV "kasvaa" ;
--     improve_VUnacc 		= mkV "kehittyä" ;
--     inflate_VUnacc 		= mkV "täyttyä" ;
--     redden_VUnacc 		= mkV "punertua" ;
--     roll_VUnacc 		= mkV "kieriä" ;
--     shorten_VUnacc 		= mkV "lyhentyä" ;
--     slide_VUnacc 		= mkV "liukua" ;
--     snap_VUnacc 		= mkV "katketa" ;
--     split_VUnacc 		= mkV "jakautua" ;

    bake_VUnerg 		= mkV {s = c52 "paistua"} ;
    call_VUnerg 		= mkV {s = c53A "soittaa"} ;
--     clean_VUnerg 		= mkV "siivota" ;
--     cook_VUnerg 		= mkV "kokata" ;
--     cry_VUnerg 		= mkV "itkeä" ;
--     dance_VUnerg 		= mkV "tanssia" ;
--     draw_VUnerg 		= mkV "piirtää" ;
--     dust_VUnerg 		= mkV "tomuttaa" ;
--     eat_VUnerg 		= mkV "syödä" ;
--     examine_VUnerg 		= mkV "tarkastella" ;
--     frown_VUnerg 		= mkV "kurtistaa" ;
--     gasp_VUnerg 		= mkV "haukkoa" ;
--     giggle_VUnerg 		= mkV "kikattaa" ;
--     hear_VUnerg 		= mkV "kuulla" ;
--     hunt_VUnerg 		= mkV "metsästää" ;
--     investigate_VUnerg 		= mkV "tutkia" ;
--     jog_VUnerg 		= mkV "hölkätä" ;
--     juggle_VUnerg 		= mkV "jongleerata" ;
--     know_VUnerg 		= mkV "tietää" ;
--     laugh_VUnerg 		= mkV "nauraa" ;
--     nap_VUnerg 		= mkV "torkkua" ;
--     notice_VUnerg 		= mkV "huomata" ;
--     nurse_VUnerg 		= mkV "hoivata" ;
--     observe_VUnerg 		= mkV "tarkkailla" ;
--     pack_VUnerg 		= mkV "pakata" ;
--     paint_VUnerg 		= mkV "maalata" ;
--     read_VUnerg 		= mkV "lukea" ;
--     run_VUnerg 		= mkV "juosta" ;
--     scoff_VUnerg 		= mkV "pilkata" ;
--     scream_VUnerg 		= mkV "kirkua" ;
--     see_VUnerg 		= mkV "nähdä" ;
--     sketch_VUnerg 		= mkV "luonnostella" ;
--     sleep_VUnerg 		= mkV "nukkua" ;
--     smile_VUnerg 		= mkV "hymyillä" ;
--     smirk_VUnerg 		= mkV "virnuilla" ;
--     sneeze_VUnerg 		= mkV "aivastaa" ;
--     snooze_VUnerg 		= mkV "torkkua" ;
--     snore_VUnerg 		= mkV "kuorsata" ;
--     study_VUnerg 		= mkV "opiskella" ;
--     stutter_VUnerg 		= mkV "änkyttää" ;
--     talk_VUnerg 		= mkV "puhua" ;
--     walk_VUnerg 		= mkV "kävellä" ;

    admire_V2 		= mkV2 (mkV {s = c67 "ihailla"}) partitive ;
    adore_V2 		= mkV2 (mkV {s = c62 "ihannoida"}) partitive ;
    appreciate_V2   = mkV2 (mkV {s = c53 "arvostaa"}) partitive ;
    bake_V2 		= mkV2 (mkV {s = c56 "paistaa"}) ;
    break_V2 		= mkV2 (mkV {s = c52A "rikkoa"}) ;
--     burn_V2 		= mkV2 "polttaa" ;
--     call_V2 		= mkV2 "soittaa" ;
--     change_V2 		= mkV2 "change" ;
--     clean_V2 		= mkV2 "clean" ;
--     collapse_V2 		= mkV2 "collapse" ;
--     cook_V2 		= mkV2 "cook" ;
--     crumple_V2 		= mkV2 "crumple" ;
--     decompose_V2 		= mkV2 "decompose" ;
--     discover_V2 		= mkV2 "discover" ;
--     disintegrate_V2 		= mkV2 "disintegrate" ;
--     double_V2 		= mkV2 "double" ;
--     draw_V2 		= mkV2 "piirtää" ;
--     dust_V2 		= mkV2 "dust" ;
--     eat_V2 		= mkV2 "syödä" ;
--     enlarge_V2 		= mkV2 "enlarge" ;
--     examine_V2 		= mkV2 "examine" ;
--     find_V2 		= mkV2 "löytää" ;
--     float_V2 		= mkV2 "float" ;
--     freeze_V2 		= mkV2 "jäädyttää" ;
--     grow_V2 		= mkV2 "kasvattaa" ;
--     hear_V2 		= mkV2 "kuulla" ;
--     help_V2 		= mkV2 "help" ;
--     hold_V2 		= mkV2 "pitää" ;
--     hunt_V2 		= mkV2 "hunt" ;
--     improve_V2 		= mkV2 "improve" ;
--     inflate_V2 		= mkV2 "inflate" ;
--     investigate_V2 		= mkV2 "investigate" ;
--     juggle_V2 		= mkV2 "juggle" ;
--     know_V2 		= mkV2 "tietää" ;
--     like_V2 		= mkV2 "like" ;
--     love_V2 		= mkV2 "love" ;
--     miss_V2 		= mkV2 "miss" ;
--     notice_V2 		= mkV2 "notice" ;
--     nurse_V2 		= mkV2 "nurse" ;
--     observe_V2 		= mkV2 "observe" ;
--     pack_V2 		= mkV2 "pack" ;
--     paint_V2 		= mkV2 "paint" ;
--     pierce_V2 		= mkV2 "pierce" ;
--     poke_V2 		= mkV2 "poke" ;
--     redden_V2 		= mkV2 "redden" ;
--     respect_V2 		= mkV2 "respect" ;
--     roll_V2 		= mkV2 "roll" ;
--     see_V2 		    = mkV2 (
--         mk12V "nähdä" "näen" "näkee" "näkevät" "nähkää" "nähdään"
--               "näin" "näki" "näkisi" "nähnyt" "nähty" "nähdyn") ;
--     shorten_V2 		= mkV2 "shorten" ;
--     sketch_V2 		= mkV2 "sketch" ;
--     slide_V2 		= mkV2  "slide" ;
--     snap_V2 		= mkV2 "snap" ;
--     split_V2 		= mkV2 "split" ;
--     stab_V2 		= mkV2 "stab" ;
--     study_V2 		= mkV2 "study" ;
--     throw_V2 		= mkV2  "throw" ;
--     tolerate_V2 		= mkV2 "tolerate" ;
--     toss_V2 		= mkV2 "toss" ;
--     touch_V2 		= mkV2 "touch" ;
--     value_V2 		= mkV2 "value" ;
--     worship_V2 		= mkV2 "worship" ;

--     award_V3doc 		= mkV3 (regV "award") noPrep noPrep ;
--     bring_V3doc 		= mkV3 (irregV "bring" "brought" "brought") noPrep noPrep ;
--     feed_V3doc 		= mkV3 (irregV "feed" "fed" "fed") noPrep noPrep ;
--     forward_V3doc 		= mkV3 (regV "forward") noPrep noPrep ;
--     give_V3doc 		= mkV3 (irregV "give" "gave" "given") noPrep noPrep ;
--     hand_V3doc 		= mkV3 (regV "hand") noPrep noPrep ;
--     lend_V3doc 		= mkV3 (irregV "lend" "lent" "lent") noPrep noPrep ;
--     loan_V3doc 		= mkV3 (regV "loan") noPrep noPrep ;
--     mail_V3doc 		= mkV3 (regV "mail") noPrep noPrep ;
--     offer_V3doc 		= mkV3 (regV "offer") noPrep noPrep ;
--     pass_V3doc 		= mkV3 (regV "pass") noPrep noPrep ;
--     post_V3doc 		= mkV3 (regV "post") noPrep noPrep ;
--     promise_V3doc 		= mkV3 (regV "promise") noPrep noPrep ;
--     rent_V3doc 		= mkV3 (regV "rent") noPrep noPrep ;
--     return_V3doc 		= mkV3 (regV "return") noPrep noPrep ;
--     sell_V3doc 		= mkV3 (irregV "sell" "sold" "sold") noPrep noPrep ;
--     send_V3doc 		= mkV3 (irregV "send" "sent" "sent") noPrep noPrep ;
--     serve_V3doc 		= mkV3 (regV "serve") noPrep noPrep ;
--     slip_V3doc 		= mkV3 (irregV "slip" "slipped" "slipped") noPrep noPrep ;
--     wire_V3doc 		= mkV3 (regV "wire") noPrep noPrep ;

--     award_to_V3 		= mkV3 (regV "award") noPrep toP ;
--     bring_to_V3 		= mkV3 (irregV "bring" "brought" "brought") noPrep toP ;
--     feed_to_V3 		= mkV3 (irregV "feed" "fed" "fed") noPrep toP ;
--     forward_to_V3 		= mkV3 (regV "forward") noPrep toP ;
    give_to_V3 		= mkV3 (mkV "antaa" "annan" "antoi") (casePrep allative) accPrep ;
--     hand_to_V3 		= mkV3 (regV "hand") noPrep toP ;
--     lend_to_V3 		= mkV3 (irregV "lend" "lent" "lent") noPrep toP ;
--     loan_to_V3 		= mkV3 (regV "loan") noPrep toP ;
--     mail_to_V3 		= mkV3 (regV "mail") noPrep toP ;
--     offer_to_V3 		= mkV3 (regV "offer") noPrep toP ;
--     pass_to_V3 		= mkV3 (regV "pass") noPrep toP ;
--     post_to_V3 		= mkV3 (regV "post") noPrep toP ;
--     promise_to_V3 		= mkV3 (regV "promise") noPrep toP ;
--     rent_to_V3 		= mkV3 (regV "rent") noPrep toP ;
--     return_to_V3 		= mkV3 (regV "return") noPrep toP ;
    sell_to_V3 		= mkV3 (mkV "myydä") accPrep (casePrep allative) ;
    send_to_V3 		= mkV3 (mkV "lähettää") accPrep (casePrep allative) ;
--     serve_to_V3 		= mkV3 (regV "serve") noPrep toP ;
--     slip_to_V3 		= mkV3 (irregV "slip" "slipped" "slipped") noPrep toP ;
--     wire_to_V3 		= mkV3 (regV "wire") noPrep toP ;

    admire_VS 		= mkVS (mkV {s = c67 "ihailla"}) ;
    appreciate_VS 		= mkVS (mkV {s = c53 "arvostaa"}) ;
--     believe_VS 		= mkVS (regV "believe") ;
--     confess_VS 		= mkVS (regV "confess") ;
--     declare_VS 		= mkVS (regV "declare") ;
--     dream_VS 		= mkVS (regV "dream") ;
--     expect_VS 		= mkVS (regV "expect") ;
    hope_VS 		= mkVS (mkV "toivoa") ;
--     imagine_VS 		= mkVS (regV "imagine") ;
--     like_VS 		= mkVS (regV "like") ;
--     mean_VS 		= mkVS (irregV "mean" "meant" "meant") ;
--     notice_VS 		= mkVS (regV "notice") ;
--     prove_VS 		= mkVS (regV "prove") ;
--     respect_VS 		= mkVS (regV "respect") ;
--     say_VS 		= mkVS (irregV "say" "said" "said") ;
--     support_VS 		= mkVS (regV "support") ;
--     think_VS 		= mkVS (irregV "think" "thought" "thought") ;
--     tolerate_VS 		= mkVS (regV "tolerate") ;
--     value_VS 		= mkVS (regV "value") ;
--     wish_VS 		= mkVS (regV "wish") ;

    attempt_VV 		= mkVV (mkV "yrittää") ;
--     crave_VV 		= mkVV {s = c74 "himota"} ;
--     dream_VV 		= mkVV (regV "dream") ;
--     enjoy_VV 		= mkVV (regV "enjoy") ;
--     expect_VV 		= mkVV (regV "expect") ;
--     hate_VV 		= mkVV (regV "hate") ;
--     hope_VV 		= mkVV (regV "hope") ;
--     intend_VV 		= mkVV (regV "intend") ;
--     itch_VV 		= mkVV (regV "itch") ;
--     like_VV 		= mkVV (regV "like") ;
--     long_VV 		= mkVV (regV "long") ;
--     love_VV 		= mkVV (mkV "rakastaa") partitive ;
--     mean_VV 		= mkVV (irregV "mean" "meant" "meant") ;
--     need_VV 		= mkVV (regV "need") ;
--     plan_VV 		= mkVV (regV "plan") ;
--     prefer_VV 		= mkVV (irregV "prefer" "preferred" "preferred") ;
--     try_VV 		= mkVV (regV "try") ;
--     wish_VV 		= mkVV (regV "wish") ;
--     yearn_VV 		= mkVV (regV "yearn") ;

    beside_Prep = mkPrep "vieressä" ;
-- oper    aboutP = mkPrep "about" ;
--     atP = mkPrep "at" ;
--     forP = mkPrep "for" ;
--     fromP = mkPrep "from" ;
    -- inP = mkPrep inessive ;
--     onP = mkPrep "on" ;
--     toP = mkPrep "to" ;
--     besideP = mkPrep "beside" ;

}
